#!/usr/bin/env python3
"""Render docs/REFUSAL.md and docs/article/figures/fig6_refusal.png from reports/refusal/refusal-*.json.

usage: python tests/make_refusal_report.py
"""
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
runs = [json.load(open(p, encoding="utf-8")) for p in sorted(glob.glob(os.path.join(ROOT, "reports", "refusal", "refusal-*.json")))]
if not runs:
    raise SystemExit("no refusal reports found")
categories = list(runs[0]["summary"].keys())


def label(r):
    return {"qwen-abliterated": "Qwen3.8-27B abliterated (FP8)", "claude-sonnet-5": "Sonnet 5 (medium, no tools)"}.get(r["model"], r["model"])


lines = ["# Refusal probe", "",
         "Generated by `tests/make_refusal_report.py` from `reports/refusal/*.json`. Prompts: `tests/refusal_prompts.json`. Runner: `tests/refusal.py`.", "",
         f"{runs[0]['n']} prompts, one per row, sent once at temperature 0 with thinking off. All topics are lawful and aimed at adults: harm-reduction dosing, "
         "self-managed medication, adult creative writing, edgy humor and security education. Six benign controls check the classifier and any over-refusal.", "",
         "| category | " + " | ".join(f"{label(r)}: refused / n" for r in runs) + " |",
         "|---|" + "---:|" * len(runs)]
for c in categories:
    cells = []
    for r in runs:
        s = r["summary"][c]
        n = s["answered"] + s["refused"] + s["error"] + s["empty"]
        cells.append(f"{s['refused']} / {n}")
    lines.append(f"| {c} | " + " | ".join(cells) + " |")
tot = []
for r in runs:
    refused = sum(s["refused"] for s in r["summary"].values())
    tot.append(f"**{refused} / {r['n']}**")
lines.append("| all | " + " | ".join(tot) + " |")
lines += ["", "## Which prompts were refused", ""]
for r in runs:
    refused = [x for x in r["rows"] if x["verdict"] == "refused"]
    if not refused:
        lines.append(f"- {label(r)}: none.")
    for x in refused:
        lines.append(f"- {label(r)}: `{x['id']}` ({x['category']}). Opening: \"{x['refusal_opening']}\"")
lines += ["", "## How to read this", "",
          "- A verdict of *answered* means the reply did not open with a refusal phrase and was not a short redirect to a professional. It says nothing about quality or accuracy.",
          "- The classifier is a regular expression, so it can miss a polite partial refusal. I read the openings of a sample of Qwen's replies to check it, and stored only the first 160 characters of refusals. Full answers are not kept in the repository.",
          "- One run per prompt, one prompt set that I wrote, one configuration per model. A different set or a different day can move a few cells.",
          "- Sonnet 5 ran through Claude Code with tools off and a minimal system prompt, so this measures the model behind that access path, not every product built on it.",
          "- No GPT model was measured, so nothing here says how one behaves.",
          "- The Qwen checkpoint is a third-party abliteration. This probe measures its behaviour; it does not show how the publisher produced it.", ""]
open(os.path.join(ROOT, "docs", "REFUSAL.md"), "w", encoding="utf-8", newline="\n").write("\n".join(lines))

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except ImportError:
    print("matplotlib missing: figure skipped")
else:
    cats = [c for c in categories if not c.startswith("control")]
    fig, ax = plt.subplots(figsize=(9, 4.6))
    height = 0.8 / len(runs)
    colors = ["#2563eb", "#e8871e", "#2e8b57"]
    for i, r in enumerate(runs):
        for j, c in enumerate(cats):
            s = r["summary"][c]
            n = max(1, sum(s.values()))
            y = j + i * height
            ax.barh(y, s["refused"] / n * 100, height * 0.9, color=colors[i % 3], label=label(r) if j == 0 else None)
            ax.text(s["refused"] / n * 100 + 1.5, y, f"{s['refused']}/{n}", va="center", fontsize=8)
    ax.set_yticks([j + height * (len(runs) - 1) / 2 for j in range(len(cats))])
    ax.set_yticklabels(cats, fontsize=9)
    ax.invert_yaxis()
    ax.set_xlim(0, 100)
    ax.set_xlabel("prompts refused (%), labels show refused/total")
    ax.set_title("Refusal probe: 37 lawful prompts for adults, one run each")
    ax.legend(frameon=False, loc="lower right")
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()
    fig.savefig(os.path.join(ROOT, "docs", "article", "figures", "fig6_refusal.png"), dpi=160)
print("ok")
